{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pg.redis.name" . }}
  labels:
    {{- include "pg.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "pg.redis.name" . }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pg.redis.name" . }}
  labels:
    {{- include "pg.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "pg.redis.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "pg.redis.name" . }}
        {{- include "pg.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
          args: ["--save", "", "--appendonly", "no"]
          livenessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
{{- end }}
